### ISSUE TITLE
HTML is not displayed correctly if search by author

### ISSUE THREAD

**Issue by alexzaitsev** [Dolu89/bitcoin-bips#13]
Sample URI: https://bips.xyz/search?q=Pieter%20Wuille
How it looks: https://drive.google.com/file/d/1pGwp8roqv5wv6UMnVecClL_IbP5RSf-H/view?usp=sharing
Using Chrome Version 98.0.4758.102 (Official Build) (x86_64)

**Comment by alexzaitsev** [comment]
You're welcome

**Comment by Dolu89** [comment]
Sorry... Thank you for the issue reporting
