### ISSUE TITLE
BIP 340 is missing - 404

### ISSUE THREAD

**Issue by sectore** [Dolu89/bitcoin-bips#20]
https://bips.xyz/340

`404 Not Found`

Original: https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki

**Comment by Dolu89** [comment]
Not related to this bip/nip specifically, but probably related to the cache.
Let's wait some days, I made a fix few days ago to change cache from 72H to infinite time.

**Comment by sectore** [comment]
> EDIT: BIP 340 has been refreshed this night

Yep, it's back again https://bips.xyz/340 :sunglasses:
