### ISSUE TITLE
Add instructions for building and running app locally

### ISSUE THREAD

**Issue by sectore** [Dolu89/bitcoin-bips#21]
Got 404 errors instead of serving pages at http://bips.local:7894 or http://127.0.0.1:7894

![404-local](https://github.com/Dolu89/bitcoin-bips/assets/47693/ec201f8a-2089-457b-923d-be1ef76ca5ee)

My setup:

```bash
# Node > 21
node -v
v21.6.1

# pnpm 8
pnpm -v
8.14.0

# Added bips.local to hosts
cat /etc/hosts
127.0.0.1   	bips.local

# Following ENV are set - some are {hidden} for privacy  
APP_URL=http://bips.local
BIPS_URL=http://bips.local
NODE_ENV=development
PORT=7894
APP_KEY={hidden}
HOST=127.0.0.1
LOG_LEVEL=debug
CACHE_VIEWS=false
GITHUB_API_KEY={hidden}
CACHE_FOLDER=./cache

# installed deps
pnpm i

# run dev
pnpm dev

```

Source code is on latest master e3b3486

Do I miss something? Please share some instruction how to build and run the app. Thanks!

**Comment by Dolu89** [comment]
Try to replace `BIPS_URL=http://bips.local` by `BIPS_URL=bips.local`
You right, I didn't write any doc since the new version, I'll do it later this week!
