### ISSUE TITLE
V2 ideas & suggestions 

### ISSUE THREAD

**Issue by Dolu89** [Dolu89/bitcoin-bips#8]
Branch : https://github.com/Dolu89/bitcoin-bips/tree/v2
Preview : https://bips-xyz.herokuapp.com/

- [ ] Projects using the current BIP
- [ ] Favorites (local storage)
- [ ] Related BIPs in each BIP (auto by discovering href or manually with JSON file)
- [ ] Last visited BIPs list
- [ ] Filters on BIPs list (home page)
- [x] Search engine
- [x] New design (UI)
- [x] No more rendering error because of Pandoc (medawiki -> HTML) issues
- [x] Automatic BIPs update
~~Show which BIPs have been modified since the last update?~~

**Comment by johnsBeharry** [comment]
Other related web content for the BIP could also be nice to have. Wether its a video explainer/talk, or blog post, or design. The content tends to stay so static after its written, it'd be great to see its impact in the space for more context.

**Comment by Bosch-0** [comment]
Would be great to be able to filter by status so I could, for example, just view all the rejected BIPs.

**Comment by Dolu89** [comment]
> Would be great to be able to filter by status so I could, for example, just view all the rejected BIPs.

Added to the list, thanks!
